# Store the spawn position for all the robots


# Number of rooms to generate (and robots to spawn)
num_rooms: 1

world_setup:
  arena_width: 10
  basic_time_step: 16
  cast_shadows: false
  floor_color: [0.8, 0.6, 0.4]

generation_params:
  room_size: 1.0
  wall_thick: 0.05
  wall_height: 0.2
  col_spacing: 3.0 # Distance between column centers (Left at -1.5, Right at 1.5)
  row_spacing: 2.0

waste_params:
  num_waste_per_room: 5
  waste_block_size: 0.03
  random_seed: 5 # < 0 for random, >= 0 for fixed seed

robot_params:
  camera_width: 33 # made it an odd number to get the center pixel
  camera_height: 33
