# Store the spawn position for all the robots

robots:
  - name: robot_1
    x: 0.0
    y: 0.0
  - name: robot_2
    x: 0.0
    y: 0.5
  - name: robot_3
    x: 0.0
    y: 1.0
  - name: robot_4
    x: 0.0
    y: 1.5
  - name: robot_5
    x: 0.0
    y: 2.0
  - name: robot_6
    x: 0.0
    y: 2.5
  - name: robot_7
    x: 0.0
    y: 3.0
  - name: robot_8
    x: 0.0
    y: 3.5
  - name: robot_9
    x: 0.0
    y: 4.0
  - name: robot_10
    x: 0.0
    y: 4.5
  - name: robot_11
    x: 0.0
    y: 5.0
  - name: robot_12
    x: 0.0
    y: 5.5